[formatter.deadnix]
command = "deadnix"
options = ["--edit"]
includes = ["*.nix"]

[formatter.nixfmt]
command = "nixfmt"
includes = ["*.nix"]

[formatter.rustfmt]
command = "rustfmt"
options = ["--config", "skip_children=true", "--edition", "2021"]
includes = ["*.rs"]

[formatter.statix]
command = "statix-fix"
includes = ["*.nix"]

[formatter.taplo]
command = "taplo"
options = ["format"]
includes = ["*.toml"]
