[book]
title = "cosmic-manager"
authors = ["HeitorAugustoLN"]
description = "Manage COSMIC desktop declaratively using home-manager"
language = "en"
multilingual = false
src = "src"

[output.html]
no-section-label = true
git-repository-url = "https://github.com/HeitorAugustoLN/cosmic-manager"
git-repository-icon = "fa-github"
